baseURL = "http://www.noahzhou.com/"
languageCode = "zh-cn"
title = "lucas.zhou `Blog"
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blogs"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 5

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[params]
    since  = 2021
    author = "lucas.zhou"                         # Author's name
    avatar = "http://www.noahzhou.com/blog-images/tx.png"    # Author's avatar
    subtitle = "A handful of summer sunshine"                    # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "full stack developer"                      # post or other
    enableGitalk = true                 # gitalk 评论系统

    google_verification = ""

    description = "夏日里的一把阳光，周光个人博客，Blog @ 周光 464032204@qq.com" # (Meta) 描述
    keywords = "周光，博客，lucas.zhou，blog，前端，全栈，后端" # site keywords

    beian = "皖ICP备17013813号-2"
    baiduAnalytics = ""
    googleAnalytics = "" # Google 统计 id

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'


[params.social]
     # GitHub = "lucas.zhou"
     # Twitter = "lucas.zhou"
     # Email   = "lucas.zhou"
     # Instagram = "xxoo"
     # Wechat = ""  # Wechat QRcode image
     # Facebook = "xxoo"
     # Telegram = "lucas.zhou"
     # Dribbble = "xxoo"
     # Medium = "xxoo"

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "" # Your client ID
    clientSecret = "" # Your client secret
    repo = "" # The repo to store comments
    owner = "" # Your GitHub ID
    admin= "" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.